### ISSUE TITLE
Can I use the repo to merge/concat multiple audio files?

### ISSUE THREAD

**Issue by zydjohnHotmail** [Mirsario/SteamAudio.NET#2]
Hello:
I have some audio files (in AAC format), which are extracted by FFMPEG from one video (MP4 format) file.  Let’s say, I have 2 of such audio files: (C:\Audios\1.aac and C:\Audios\2.aac), I want to merge or concat them into one audio file: C:\Audios\merge.aac.
Can I use the repo to do this?
If yes, please share some C# code.  I am using Visual Studio 2022 for targeting .NET 6.0 on Windows 10.
I can use FFMPEG to do this, unfortunately, FFMPEG is rather bad in processing audio files.  For example, if the original video file has the duration of 1 minute, the audio file extracted from the video has never has the duration of 1 minute, it could be something like: 1.5 minute or others.  Any way, it is not suitable for production.
Let me know if I can use the repo to do the job.
Thanks,

**Comment by Mirsario** [comment]
🤔

That is not at all what [Steam Audio](https://valvesoftware.github.io/steam-audio) is about. It's a library for runtime 3D audio processing for videogames - [HRTF](https://en.wikipedia.org/wiki/Head-related_transfer_function), sound bouncing simulations, etc.

What you're describing you can just do with a tool like [Audacity](https://www.audacityteam.org/), if not programmatically.
